---
- name: restart docker
  systemd:
    name: docker
    enabled: yes
    daemon_reload: yes
    state: restarted

- name: reload docker
  systemd:
    name: docker
    enabled: yes
    daemon_reload: yes
    state: reloaded