---
- name: restart keepalived
  systemd:  name=keepalived state=restarted  enabled=yes daemon_reload=yes

- name: start keepalived
  systemd:  name=keepalived state=started  enabled=yes daemon_reload=yes