---
- name: install base components for all hosts
  hosts: k8s-cluster
  any_errors_fatal: true
  roles:
    - { role: bootstrap-os }
    - { role: docker }
    - { role: kubernetes/base }

- hosts: kube-masters
  any_errors_fatal: true
  roles:
    - { role: keepalived, tags: keepalived }

- hosts: kube-masters
  gather_facts: true
  any_errors_fatal: true
  serial: 1
  roles:
    - { role: kubernetes/master, tags: master }
    - { role: kubernetes/client, tags: client }

- hosts: kube-nodes
  gather_facts: true
  any_errors_fatal: true
  roles:
    - { role: kubernetes/node, tags: node }

- hosts: kube-masters[0]
  gather_facts: true
  any_errors_fatal: true
  roles:
    - { role: cni/flannel, tags: flannel, when: cni_type == "flannel" }